export const SET_CURRENT_USER = 'SET_CURRENT_USER';

const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const flashMessageConstants = {
  ADD_FLASH_MESSAGE,
  DELETE_FLASH_MESSAGE,
};

